# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        
      # Install Node
      - name: Install Node
        uses: actions/checkout@v3
        with:
          node-version: '18'
          cache: npm

      # Install newman
      - name: Install newman
        run: |
          npm install -g newman
          npm install -g newman-reporter-htmlextra

      # Make directory to upload the test results
      - name: Make directory for uploading the test results
        run: mkdir -p test_results

      # Run collection
      - name: Run collection
        run: |
          newman run "collections/collection.json" -e "collections/environment.json" -g "collections/globals.json" -r htmlextra --reporter-htmlextra-export test_results/test_report.html0
          
      # Publish report
      - name: Publish report
        uses: actions/checkout@v3
        with:
          name: test-run-reports
          path: test_results
